import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import * as path from 'path';

// Load environment variables from .env
dotenv.config({ path: path.resolve(process.cwd(), '.env') });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error('Missing Supabase environment variables in .env');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
const BUCKET = 'ginex-assets';
const FOLDERS = ['products', 'categories', 'brands'];

async function main() {
  const isForce = process.argv.includes('--force');

  console.log(`\n🔍 Starting image cleanup script... (Mode: ${isForce ? 'FORCE DELETE' : 'DRY RUN'})\n`);

  // 1. Gather all used URLs from DB
  console.log('Fetching database records...');
  
  const [
    { data: products, error: pErr },
    { data: categories, error: cErr },
    { data: brands, error: bErr }
  ] = await Promise.all([
    supabase.from('products').select('featured_image_url, images'),
    supabase.from('categories').select('image_url'),
    supabase.from('brands').select('logo_url')
  ]);

  if (pErr || cErr || bErr) {
    console.error('Error fetching data:', { pErr, cErr, bErr });
    process.exit(1);
  }

  // Extract all URLs
  const usedPaths = new Set<string>();

  const extractPath = (url: string | null | undefined) => {
    if (!url || url === 'null') return;
    try {
      const parts = url.split(`/${BUCKET}/`);
      if (parts.length > 1) {
        usedPaths.add(parts[1]);
      }
    } catch (e) {
      // ignore parsing errors
    }
  };

  products?.forEach(p => {
    extractPath(p.featured_image_url);
    if (Array.isArray(p.images)) {
      p.images.forEach((imgUrl: string) => extractPath(imgUrl));
    }
  });

  categories?.forEach(c => extractPath(c.image_url));
  brands?.forEach(b => extractPath(b.logo_url));

  console.log(`Found ${usedPaths.size} unique image paths currently used in DB.\n`);

  // 2. Gather all files in storage
  console.log('Fetching files from storage bucket...');
  const filesToDelete: string[] = [];

  for (const folder of FOLDERS) {
    const { data: files, error } = await supabase.storage.from(BUCKET).list(folder, {
      limit: 10000,
      search: '',
    });

    if (error) {
      console.error(`Error listing folder ${folder}:`, error);
      continue;
    }

    if (!files) continue;

    for (const file of files) {
      // .emptyFolderPlaceholder is generated by Supabase sometimes
      if (file.name === '.emptyFolderPlaceholder') continue;
      
      const fullPath = `${folder}/${file.name}`;
      
      if (!usedPaths.has(fullPath)) {
        filesToDelete.push(fullPath);
      }
    }
  }

  console.log(`\n🔎 Analysis Complete: Found ${filesToDelete.length} unused files.\n`);

  if (filesToDelete.length === 0) {
    console.log('✨ Your storage is perfectly clean! No orphaned images found.');
    return;
  }

  console.log('Files scheduled for deletion:');
  filesToDelete.forEach((f, i) => console.log(`  ${i + 1}. ${f}`));
  console.log('');

  // 3. Execution
  if (isForce) {
    console.log(`🗑️ Deleting ${filesToDelete.length} files...`);
    const { data, error } = await supabase.storage.from(BUCKET).remove(filesToDelete);
    
    if (error) {
      console.error('❌ Failed to delete files:', error);
    } else {
      console.log(`✅ Successfully deleted ${data?.length || 0} files.`);
    }
  } else {
    console.log('⚠️ DRY RUN COMPLETED.');
    console.log('To actually delete these files, run the script with the --force flag:');
    console.log('  npx tsx scripts/cleanup-images.ts --force\n');
  }
}

main().catch(console.error);
